start Powershell.exe
start https://www.youtube.com/watch?v=dQw4w9WgXcQ
start Powershell.exe
start cmd
start Powershell.exe
start cmd
start Powershell.exe
start cmd
start Powershell.exe
start cmd
start Powershell.exe
start cmd
start Powershell.exe
start cmd
start Powershell.exe
start cmd
start Powershell.exe
start cmd
start Powershell.exe
start cmd
start Powershell.exe
start cmd
start Powershell.exe
start cmd
start notepad
start notepad
start notepad
start notepad
start notepad
start notepad
start notepad
start notepad
start notepad
start notepad
start notepad
start notepad
start notepad
start notepad
start notepad
start notepad
start notepad
start notepad
start notepad
start notepad
start notepad
start notepad
start notepad
start notepad
start notepad
start notepad
start notepad
start notepad
start notepad
start notepad
start notepad
start notepad
start notepad
start notepad
start notepad
start notepad
start notepad
start notepad
start notepad
start notepad
start notepad
start notepad
start notepad
start notepad
start notepad
start notepad
start notepad
start notepad
start notepad
start notepad
start notepad
taskkill /im cmd.exe /t /f
taskkill /im Powershell.exe /t /f
taskkill /im notepad.exe /t /f
cls
exit
